/*
==========================================================================================
Magnitude Analysis
==========================================================================================
Purpose:
	- To analyze the magnitude.

What is Magnitude analysis?
It compares Measure values by Categories and help us understand importance of different categories.

SQL Function used:
	-Count
	-sum
	-group by
	-order by
	-avg

*/

-- Find total customers by countries
select
	country,
	count(customer_key) as total_customers
from 
	gold.dim_customers
group by 
	country
order by 
	total_customers desc

-- Find total customers by genders
select 
	gender,
	count(customer_key) as total_customers
from 
	gold.dim_customers
group by 
	gender
order by 
	total_customers desc

-- Find total products by category
select
	category,
	count(product_key) as total_products
from 
	gold.dim_products
group by 
	category
order by 
	total_products desc

-- What is the average cost in each category?
select
	category,
	avg(cost) as avg_cost
from 
	gold.dim_products
group by 
	category
order by 
	avg_cost desc

-- What is total revenue generated for each category?
select
	p.category,
	sum(f.sales_amount) as total_revenue
from 
	gold.fact_sales f
left join 
	gold.dim_products p
on 
	p.product_key = f.product_key
group by 
	p.category
order by 
	total_revenue desc

-- Find total revenue generated by each customer
select
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) as total_revenue
from
	gold.fact_sales f
left join 
	gold.dim_customers c
on 
	c.customer_key = f.customer_key
group by 
	c.customer_key,
	c.first_name,
	c.last_name
order by 
	total_revenue desc

-- What is the distribution of sold items across the countries?
select 
	c.country,
	sum(f.quantity) as total_sold_items
from 
	gold.dim_customers c
left join 
	gold.fact_sales f
on 
	c.customer_key = f.customer_key
group by 
	c.country
order by 
	total_sold_items desc